apiVersion: v1
kind: Template
metadata:
  name: simple-dc-template
  annotations:
    openshift.io/display-name: "Simple Server Deployment"
    iconClass: "icon-go-gopher"
    description: "A very simple template for a simple server deployment"
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: simple-dc
    spec:
      replicas: 2
      selector:
        name: "simple"
      template:
        metadata:
          labels:
            name: "simple"
        spec:
          containers:
          - env:
            - name: CUSTOM_VARIABLE
              value: ${CUSTOM_VARIABLE}
            image: 172.30.1.1:5000/adm-project/simple
            name: simple-container
            ports:
            - containerPort: 8080
              protocol: TCP
      triggers:
      - type: ConfigChange
      - type: "ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
          - simple-container
          from:
            kind: ImageStreamTag
            name: simple:latest
parameters:
  - name: CUSTOM_VARIABLE
    description: "selbst gewählte Variable, abrufbar unter /custom-variable"
    from: '[A-Za-z0-9 ]*'
    generate: expression   
labels:
  template: "simple-dc"
