apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-bc
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-bc:latest'
  source:
    git:
      uri: 'https://github.com/BloodyRainer/simple'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-go:latest'
  triggers:
    - type: GitHub
      github:
        secret: GjK1N7CuhR8A_LE-KXte