apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-app
  namespace: ravo-test
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'simple-app:latest'
  source:
    git:
      uri: 'https://github.com/BloodyRainer/simple'
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-go:latest'
        namespace: ravo-test
  triggers:
    - type: GitHub
      github:
        secret: GjK1N7CuhR8A_LE-KXte
    - generic:
        secret: Wn_ph_sAfJ6lDIXhw1O0
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          ravo444/s2i-go@sha256:f1c4c39782de08e07d0874ce85680e9686ab7107d806d6f5a1e5302885990032
      type: ImageChange
status:
  lastVersion: 1